version: '3'

services:
  nginx-web:
    image: nginx:1.23.4
    container_name: nginx-web
    restart: always
    environment:
      # 时区上海
      TZ: Asia/Shanghai
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # 证书映射
      - ~/tixwork/nginx/cert:/etc/nginx/cert
      # 配置文件映射
      - ~/tixwork/nginx/nginx.conf:/etc/nginx/nginx.conf
      # 页面目录
      - ~/tixwork/nginx/content:/usr/share/nginx/html
      # 日志目录
      - ~/tixwork/nginx/log:/var/log/nginx
