--- #设置dbrunner
dbrunner:
  enabled: true
  auto-patch: true

--- # 验证码
captcha.enable: false

--- # 密码错误
user.password.maxRetryCount: 50

--- # 监控中心配置
spring.boot.admin.client:
  # 增加客户端开关
  enabled: true
  url: http://localhost:8090/admin
  instance:
    service-host-type: IP
  username: tixwork
  password: xxxxxx

--- # xxl-job 配置
xxl.job:
  # 执行器开关
  enabled: false
  # 调度中心地址：如调度中心集群部署存在多个地址则用逗号分隔。
  admin-addresses: http://localhost:9100/xxl-job-admin
  # 执行器通讯TOKEN：非空时启用
  access-token: xxl-job
  executor:
    # 执行器AppName：执行器心跳注册分组依据；为空则关闭自动注册
    appname: xxl-job-executor
    # 执行器端口号 执行器从9101开始往后写
    port: 9101
    # 执行器注册：默认IP:PORT
    address:
    # 执行器IP：默认自动获取IP
    ip:
    # 执行器运行日志文件存储磁盘路径
    logpath: ./logs/xxl-job
    # 执行器日志文件保存天数：大于3生效
    logretentiondays: 30

--- # 数据源配置
spring:
  datasource:
    dynamic:
      p6spy: true
      datasource:
        master:
          driverClassName: org.postgresql.Driver
          url: jdbc:postgresql://localhost:5432/${biz.name}-dev?stringtype=unspecified&useUnicode=true&characterEncoding=utf8&useSSL=true&autoReconnect=true&reWriteBatchedInserts=true
          username: root
          password: xxxxxx
--- # redis 单机配置(单机与集群只能开启一个另一个需要注释掉)
spring.data:
  redis:
    #    host: 139.186.155.122
    host: localhost
    port: 6379
    database: 0
    password: xxxxxx
    timeout: 10s
    ssl.enabled: false

--- # security配置
security:
  # 排除路径
  excludes:
    # 公共路径
    - /favicon.ico
    - /error
    # docs
    - /*/api-docs
    - /*/api-docs/**
    # actuator 监控配置
    - /actuator
    - /actuator/**

--- # docs 接口文档
springdoc.api-docs.enabled: true
