export default [
  {
    // name: '项目信息管理',
    // icon: 'iconfont-redis',
    path: '/cdsz/project-info',
    component: './generic-page/listof-page.tsx',
  },
  {
    // name: '项目信息详情',
    // icon: 'iconfont-redis',
    hideInMenu: true,
    path: '/cdsz/project-info/:id',
    component: './generic-page/detail-page.tsx',
  },
  {
    // name: '招商拜访情况',
    // icon: 'iconfont-scheduler',
    path: '/cdsz/visit-record',
    component: './generic-page/listof-page.tsx',
  },
  {
    // name: '招商拜访情况详情',
    // icon: 'iconfont-scheduler',
    hideInMenu: true,
    path: '/cdsz/visit-record/:id',
    component: './generic-page/detail-page.tsx',
  },
  {
    // name: '企业联络信息',
    // icon: 'iconfont-menu',
    path: '/cdsz/company-contact',
    component: './generic-page/listof-page.tsx',
  },
  {
    // name: '企业联络信息详情',
    // icon: 'iconfont-menu',
    hideInMenu: true,
    path: '/cdsz/company-contact/:id',
    component: './generic-page/detail-page.tsx',
  },
  {
    // name: '政务点位管理',
    // icon: 'iconfont-user',
    path: '/cdsz/government-affairs-location',
    component: './generic-page/listof-page.tsx',
  },
  {
    // name: '政务点位详情',
    // icon: 'iconfont-user',
    hideInMenu: true,
    path: '/cdsz/government-affairs-location/:id',
    component: './generic-page/detail-page.tsx',
  },
  {
    // name: '接待酒店管理',
    // icon: 'iconfont-home',
    path: '/cdsz/hotel',
    component: './generic-page/listof-page.tsx',
  },
  {
    // name: '接待酒店详情',
    // icon: 'iconfont-home',
    hideInMenu: true,
    path: '/cdsz/hotel/:id',
    component: './generic-page/detail-page.tsx',
  },
  {
    // name: '接待餐厅管理',
    // icon: 'iconfont-cart2',
    path: '/cdsz/restaurant',
    component: './generic-page/listof-page.tsx',
  },
  {
    // name: '接待餐厅详情',
    // icon: 'iconfont-cart2',
    hideInMenu: true,
    path: '/cdsz/restaurant/:id',
    component: './generic-page/detail-page.tsx',
  },
];
