export default [
  {
    // name: '历程管理',
    // icon: 'iconfont-icon_share',
    path: '/engineseals/course-record',
    component: './generic-page/listof-page.tsx',
  },
  {
    // name: '历程详情',
    // icon: 'iconfont-cloud-download',
    hideInMenu: true,
    path: '/engineseals/course-record/:id',
    component: './generic-page/detail-page.tsx',
  },
  {
    // name: '出厂信息管理',
    // icon: 'iconfont-warning-circle',
    path: '/engineseals/factory-information',
    component: './generic-page/listof-page.tsx',
  },
  {
    // name: '出厂信息详情',
    // icon: 'iconfont-home',
    hideInMenu: true,
    path: '/engineseals/factory-information/:id',
    component: './generic-page/detail-page.tsx',
  },
  {
    // name: '装配信息管理',
    // icon: 'iconfont-notice',
    path: '/engineseals/assemble-info',
    component: './generic-page/listof-page.tsx',
  },
  {
    // name: '装配信息详情',
    // icon: 'iconfont-notice',
    hideInMenu: true,
    path: '/engineseals/assemble-info/:id',
    component: './generic-page/detail-page.tsx',
  },
  {
    // name: '分解信息管理',
    // icon: 'iconfont-home',
    path: '/engineseals/dismantling-info',
    component: './generic-page/listof-page.tsx',
  },
  {
    // name: '分解信息详情',
    // icon: 'iconfont-icon_edit',
    hideInMenu: true,
    path: '/engineseals/dismantling-info/:id',
    component: './generic-page/detail-page.tsx',
  },
  {
    // name: '试验信息管理',
    // icon: 'iconfont-clock',
    path: '/engineseals/experimental-info',
    component: './generic-page/listof-page.tsx',
  },
  {
    // name: '试验信息详情',
    // icon: 'iconfont-scan',
    hideInMenu: true,
    path: '/engineseals/experimental-info/:id',
    component: './generic-page/detail-page.tsx',
  },
  {
    // name: '故障信息管理',
    // icon: 'iconfont-plus',
    path: '/engineseals/trouble-info',
    component: './generic-page/listof-page.tsx',
  },
  {
    // name: '故障信息详情',
    // icon: 'iconfont-app-more',
    hideInMenu: true,
    path: '/engineseals/trouble-info/:id',
    component: './generic-page/detail-page.tsx',
  },
  {
    // name: '出入库记录管理',
    // icon: 'iconfont-plus',
    path: '/engineseals/inventory-record',
    component: './generic-page/listof-page.tsx',
  },
  {
    // name: '出入库记录详情',
    // icon: 'iconfont-search',
    hideInMenu: true,
    path: '/engineseals/inventory-record/:id',
    component: './generic-page/detail-page.tsx',
  },
  {
    // name: '配件维修记录',
    // icon: 'iconfont-icon_edit',
    path: '/engineseals/repair-record',
    component: './generic-page/listof-page.tsx',
  },
  {
    // name: '配件维修记录详情',
    // icon: 'iconfont-icon_share',
    hideInMenu: true,
    path: '/engineseals/repair-record/:id',
    component: './generic-page/detail-page.tsx',
  },
  {
    // name: '发动机型号管理',
    // icon: 'iconfont-right',
    path: '/engineseals/engine-model',
    component: './generic-page/listof-page.tsx',
  },
  {
    // name: '发动机型号详情',
    // icon: 'iconfont-right',
    hideInMenu: true,
    path: '/engineseals/engine-model/:id',
    component: './generic-page/detail-page.tsx',
  },
  {
    // name: '发动机台份管理',
    // icon: 'iconfont-me',
    path: '/engineseals/engine',
    component: './generic-page/listof-page.tsx',
  },
  {
    // name: '发动机台份详情',
    // icon: 'iconfont-notice',
    hideInMenu: true,
    path: '/engineseals/engine/:id',
    component: './generic-page/detail-page.tsx',
  },
  {
    // name: '试验器管理',
    // icon: 'iconfont-iconfont',
    path: '/engineseals/experimental-device',
    component: './generic-page/listof-page.tsx',
  },
  {
    // name: '试验器详情',
    // icon: 'iconfont-notice',
    hideInMenu: true,
    path: '/engineseals/experimental-device/:id',
    component: './generic-page/detail-page.tsx',
  },
  {
    // name: '位置库管理',
    // icon: 'iconfont-heart',
    path: '/engineseals/location',
    component: './generic-page/listof-page.tsx',
  },
  {
    // name: '位置库详情',
    // icon: 'iconfont-eye',
    hideInMenu: true,
    path: '/engineseals/location/:id',
    component: './generic-page/detail-page.tsx',
  },
  {
    // name: '润滑件管理',
    // icon: 'iconfont-icon_edit',
    path: '/engineseals/ext-type1',
    component: './generic-page/listof-page.tsx',
  },
  {
    // name: '润滑件详情',
    // icon: 'iconfont-iconfont',
    hideInMenu: true,
    path: '/engineseals/ext-type1/:id',
    component: './generic-page/detail-page.tsx',
  },
  {
    // name: '轴承件管理',
    // icon: 'iconfont-search',
    path: '/engineseals/ext-type2',
    component: './generic-page/listof-page.tsx',
  },
  {
    // name: '轴承件详情',
    // icon: 'iconfont-scan',
    hideInMenu: true,
    path: '/engineseals/ext-type2/:id',
    component: './generic-page/detail-page.tsx',
  },
  {
    // name: '传动件管理',
    // icon: 'iconfont-icon_share',
    path: '/engineseals/ext-type3',
    component: './generic-page/listof-page.tsx',
  },
  {
    // name: '传动件详情',
    // icon: 'iconfont-app-2',
    hideInMenu: true,
    path: '/engineseals/ext-type3/:id',
    component: './generic-page/detail-page.tsx',
  },
  {
    // name: '密封件管理',
    // icon: 'iconfont-file-image',
    path: '/engineseals/accessories',
    component: './generic-page/listof-page.tsx',
  },
  {
    // name: '密封件详情',
    // icon: 'iconfont-warning-circle',
    hideInMenu: true,
    path: '/engineseals/accessories/:id',
    component: './generic-page/detail-page.tsx',
  },
  {
    // name: '性能参数管理',
    // icon: 'iconfont-app-more',
    path: '/engineseals/dyn-field',
    component: './generic-page/listof-page.tsx',
  },
  {
    // name: '性能参数详情',
    // icon: 'iconfont-eye',
    hideInMenu: true,
    path: '/engineseals/dyn-field/:id',
    component: './generic-page/detail-page.tsx',
  },
  {
    // name: '密封类型管理',
    // icon: 'iconfont-icon_share',
    path: '/engineseals/seal-type',
    component: './generic-page/listof-page.tsx',
  },
  {
    // name: '密封类型详情',
    // icon: 'iconfont-app-2',
    hideInMenu: true,
    path: '/engineseals/seal-type/:id',
    component: './generic-page/detail-page.tsx',
  },
  {
    // name: '密封部位管理',
    // icon: 'iconfont-icon_edit',
    path: '/engineseals/seal-part',
    component: './generic-page/listof-page.tsx',
  },
  {
    // name: '密封部位详情',
    // icon: 'iconfont-me',
    hideInMenu: true,
    path: '/engineseals/seal-part/:id',
    component: './generic-page/detail-page.tsx',
  },
  {
    // name: '摩擦副管理',
    // icon: 'iconfont-app-more',
    path: '/engineseals/friction-pair',
    component: './generic-page/listof-page.tsx',
  },
  {
    // name: '摩擦副详情',
    // icon: 'iconfont-heart-2',
    hideInMenu: true,
    path: '/engineseals/friction-pair/:id',
    component: './generic-page/detail-page.tsx',
  },
  {
    // name: '材料管理',
    // icon: 'iconfont-app-more',
    path: '/engineseals/material',
    component: './generic-page/listof-page.tsx',
  },
  {
    // name: '材料详情',
    // icon: 'iconfont-icon_edit',
    hideInMenu: true,
    path: '/engineseals/material/:id',
    component: './generic-page/detail-page.tsx',
  },
  {
    // name: '供应商管理',
    // icon: 'iconfont-icon_edit',
    path: '/engineseals/supplier',
    component: './generic-page/listof-page.tsx',
  },
  {
    // name: '供应商详情',
    // icon: 'iconfont-cloud-download',
    hideInMenu: true,
    path: '/engineseals/supplier/:id',
    component: './generic-page/detail-page.tsx',
  },
];
